import { execFile as execFileCb } from 'child_process'
import { promisify } from 'util'

const execFile = promisify(execFileCb)

/** Timeout in milliseconds for all yt-dlp subprocess calls. */
const TIMEOUT_MS = 30_000

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface SubtitleTrack {
  lang: string
  name: string
  isAutoGenerated: boolean
}

export interface DownloadSubOpts {
  lang: string
  format: string
  autoGenerated: boolean
  outputDir: string
}

// ---------------------------------------------------------------------------
// Pure helpers (no I/O)
// ---------------------------------------------------------------------------

/**
 * Validates a YouTube video ID.
 * Accepts alphanumeric characters, hyphens, and underscores, 1-20 chars.
 * Rejects empty strings, URLs, and strings with spaces.
 */
export function validateVideoId(id: string): boolean {
  return /^[a-zA-Z0-9_-]{1,20}$/.test(id)
}

/**
 * Builds the yt-dlp CLI argument array for downloading subtitles.
 */
export function buildSubArgs(videoId: string, opts: DownloadSubOpts): string[] {
  const writeFlag = opts.autoGenerated ? '--write-auto-sub' : '--write-sub'
  const outputTemplate = `${opts.outputDir}/%(id)s.%(sub_lang)s.%(ext)s`
  const url = `https://www.youtube.com/watch?v=${videoId}`

  return [
    writeFlag,
    '--sub-lang',
    opts.lang,
    '--sub-format',
    opts.format,
    '--skip-download',
    '-o',
    outputTemplate,
    url,
  ]
}

/**
 * Parses the JSON output from `yt-dlp --dump-json` into SubtitleTrack[].
 *
 * - `json.subtitles`          -> tracks with isAutoGenerated = false
 * - `json.automatic_captions` -> tracks with isAutoGenerated = true
 *
 * For each language key the first item's `name` is used, falling back to
 * the language code itself.
 */
export function parseListSubsOutput(json: Record<string, unknown>): SubtitleTrack[] {
  const tracks: SubtitleTrack[] = []

  const parseLangMap = (
    map: unknown,
    isAutoGenerated: boolean,
  ): void => {
    if (!map || typeof map !== 'object') return
    const langMap = map as Record<string, unknown[]>
    for (const lang of Object.keys(langMap)) {
      const entries = langMap[lang]
      if (!Array.isArray(entries) || entries.length === 0) continue
      const first = entries[0] as Record<string, unknown> | undefined
      const name = (first && typeof first.name === 'string' ? first.name : lang)
      tracks.push({ lang, name, isAutoGenerated })
    }
  }

  parseLangMap(json.subtitles, false)
  parseLangMap(json.automatic_captions, true)

  return tracks
}

// ---------------------------------------------------------------------------
// Async functions (I/O — call yt-dlp)
// ---------------------------------------------------------------------------

/**
 * Checks that the `yt-dlp` binary is available on $PATH.
 * Throws a descriptive error if not found.
 */
export async function checkYtdlp(): Promise<void> {
  try {
    await execFile('yt-dlp', ['--version'], { timeout: TIMEOUT_MS })
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : String(err)
    throw new Error(
      `yt-dlp is not installed or not found on PATH. Please install it (https://github.com/yt-dlp/yt-dlp). Details: ${message}`,
    )
  }
}

/**
 * Lists all available subtitle tracks for a video.
 */
export async function listSubs(videoId: string): Promise<SubtitleTrack[]> {
  if (!validateVideoId(videoId)) {
    throw new Error(`Invalid video ID: ${videoId}`)
  }

  const { stdout } = await execFile(
    'yt-dlp',
    ['--dump-json', '--skip-download', `https://www.youtube.com/watch?v=${videoId}`],
    { timeout: TIMEOUT_MS },
  )

  const json = JSON.parse(stdout) as Record<string, unknown>
  return parseListSubsOutput(json)
}

/**
 * Downloads subtitles for a video and returns the expected output file path.
 */
export async function downloadSubs(
  videoId: string,
  opts: DownloadSubOpts,
): Promise<string> {
  if (!validateVideoId(videoId)) {
    throw new Error(`Invalid video ID: ${videoId}`)
  }

  const args = buildSubArgs(videoId, opts)
  await execFile('yt-dlp', args, { timeout: TIMEOUT_MS })

  return `${opts.outputDir}/${videoId}.${opts.lang}.${opts.format}`
}

/**
 * Fetches full video metadata as a JSON object.
 */
export async function getVideoInfo(
  videoId: string,
): Promise<Record<string, unknown>> {
  if (!validateVideoId(videoId)) {
    throw new Error(`Invalid video ID: ${videoId}`)
  }

  const { stdout } = await execFile(
    'yt-dlp',
    ['--dump-json', '--skip-download', `https://www.youtube.com/watch?v=${videoId}`],
    { timeout: TIMEOUT_MS },
  )

  return JSON.parse(stdout) as Record<string, unknown>
}
