import {
  validateVideoId,
  buildSubArgs,
  parseListSubsOutput,
  DownloadSubOpts,
} from './ytdlp'

describe('validateVideoId', () => {
  it('accepts a standard 11-char video ID', () => {
    expect(validateVideoId('dQw4w9WgXcQ')).toBe(true)
  })

  it('accepts IDs with hyphens', () => {
    expect(validateVideoId('abc-def_123')).toBe(true)
  })

  it('accepts IDs with underscores', () => {
    expect(validateVideoId('a_b_c_d_e_f')).toBe(true)
  })

  it('rejects empty string', () => {
    expect(validateVideoId('')).toBe(false)
  })

  it('rejects strings with spaces', () => {
    expect(validateVideoId('abc def')).toBe(false)
  })

  it('rejects full URLs', () => {
    expect(validateVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).toBe(false)
  })

  it('rejects strings longer than 20 chars', () => {
    expect(validateVideoId('a'.repeat(21))).toBe(false)
  })

  it('accepts single character ID', () => {
    expect(validateVideoId('a')).toBe(true)
  })

  it('accepts 20 character ID (max length)', () => {
    expect(validateVideoId('a'.repeat(20))).toBe(true)
  })
})

describe('buildSubArgs', () => {
  const baseOpts: DownloadSubOpts = {
    lang: 'en',
    format: 'vtt',
    autoGenerated: false,
    outputDir: '/tmp/subs',
  }

  it('uses --write-sub in normal mode', () => {
    const args = buildSubArgs('dQw4w9WgXcQ', baseOpts)
    expect(args).toContain('--write-sub')
    expect(args).not.toContain('--write-auto-sub')
  })

  it('uses --write-auto-sub when autoGenerated is true', () => {
    const args = buildSubArgs('dQw4w9WgXcQ', { ...baseOpts, autoGenerated: true })
    expect(args).toContain('--write-auto-sub')
    expect(args).not.toContain('--write-sub')
  })

  it('includes --sub-lang with the specified language', () => {
    const args = buildSubArgs('dQw4w9WgXcQ', baseOpts)
    const langIdx = args.indexOf('--sub-lang')
    expect(langIdx).toBeGreaterThanOrEqual(0)
    expect(args[langIdx + 1]).toBe('en')
  })

  it('includes --sub-format with the specified format', () => {
    const args = buildSubArgs('dQw4w9WgXcQ', baseOpts)
    const fmtIdx = args.indexOf('--sub-format')
    expect(fmtIdx).toBeGreaterThanOrEqual(0)
    expect(args[fmtIdx + 1]).toBe('vtt')
  })

  it('includes --skip-download', () => {
    const args = buildSubArgs('dQw4w9WgXcQ', baseOpts)
    expect(args).toContain('--skip-download')
  })

  it('includes -o with correct output template', () => {
    const args = buildSubArgs('dQw4w9WgXcQ', baseOpts)
    const oIdx = args.indexOf('-o')
    expect(oIdx).toBeGreaterThanOrEqual(0)
    expect(args[oIdx + 1]).toBe('/tmp/subs/%(id)s.%(sub_lang)s.%(ext)s')
  })

  it('appends the video URL at the end', () => {
    const args = buildSubArgs('dQw4w9WgXcQ', baseOpts)
    expect(args[args.length - 1]).toBe('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
  })
})

describe('parseListSubsOutput', () => {
  it('parses subtitles as non-auto-generated tracks', () => {
    const json = {
      subtitles: {
        en: [{ name: 'English', ext: 'vtt' }],
        fr: [{ name: 'French', ext: 'vtt' }],
      },
    }
    const tracks = parseListSubsOutput(json)
    const manualTracks = tracks.filter((t) => !t.isAutoGenerated)
    expect(manualTracks).toHaveLength(2)
    expect(manualTracks).toEqual(
      expect.arrayContaining([
        { lang: 'en', name: 'English', isAutoGenerated: false },
        { lang: 'fr', name: 'French', isAutoGenerated: false },
      ]),
    )
  })

  it('parses automatic_captions as auto-generated tracks', () => {
    const json = {
      automatic_captions: {
        en: [{ name: 'English (auto)', ext: 'vtt' }],
      },
    }
    const tracks = parseListSubsOutput(json)
    expect(tracks).toHaveLength(1)
    expect(tracks[0]).toEqual({
      lang: 'en',
      name: 'English (auto)',
      isAutoGenerated: true,
    })
  })

  it('combines both subtitles and automatic_captions', () => {
    const json = {
      subtitles: {
        en: [{ name: 'English', ext: 'vtt' }],
      },
      automatic_captions: {
        ja: [{ name: 'Japanese (auto)', ext: 'vtt' }],
      },
    }
    const tracks = parseListSubsOutput(json)
    expect(tracks).toHaveLength(2)
    expect(tracks).toEqual(
      expect.arrayContaining([
        { lang: 'en', name: 'English', isAutoGenerated: false },
        { lang: 'ja', name: 'Japanese (auto)', isAutoGenerated: true },
      ]),
    )
  })

  it('falls back to lang code when name is missing', () => {
    const json = {
      subtitles: {
        en: [{ ext: 'vtt' }],
      },
    }
    const tracks = parseListSubsOutput(json)
    expect(tracks).toHaveLength(1)
    expect(tracks[0]).toEqual({
      lang: 'en',
      name: 'en',
      isAutoGenerated: false,
    })
  })

  it('returns empty array for empty subtitles/captions', () => {
    const json = {
      subtitles: {},
      automatic_captions: {},
    }
    const tracks = parseListSubsOutput(json)
    expect(tracks).toEqual([])
  })

  it('returns empty array when fields are missing', () => {
    const tracks = parseListSubsOutput({})
    expect(tracks).toEqual([])
  })

  it('returns empty array for completely empty object', () => {
    const tracks = parseListSubsOutput({})
    expect(tracks).toEqual([])
  })
})
