import { Command } from 'commander'
import { loadConfig, resolveHome } from '../../config'
import { listLanguages, fetchSubtitles, searchInSubtitles, parseSrt } from './service'
import { renderLanguagesTable, renderSearchResults } from './ui'
import { SUBTITLE_FORMATS } from './types'
import type { SubtitleFormat, SubtitlesCfg } from './types'

interface SubtitlesOpts {
  format?: string
  lang?: string
  auto: boolean
  list: boolean
  search?: string
  output?: string
  stdout: boolean
  ascii: boolean
}

export const subtitlesCommand = new Command('subtitles')
  .description('Download and search YouTube video subtitles')
  .argument('<videoId>', 'YouTube video ID')
  .option('-f, --format <fmt>', `subtitle format (${SUBTITLE_FORMATS.join('|')})`)
  .option('-l, --lang <code>', 'subtitle language code')
  .option('--auto', 'prefer auto-generated subtitles', false)
  .option('--list', 'list available subtitle languages', false)
  .option('--search <query>', 'search text in subtitles with timestamps')
  .option('-o, --output <path>', 'output directory path')
  .option('--stdout', 'print subtitles to stdout instead of saving', false)
  .option('--ascii', 'force ASCII table', false)
  .action(async (videoId: string, opts: SubtitlesOpts) => {
    const config = loadConfig()

    // --list mode
    if (opts.list) {
      const tracks = await listLanguages(videoId)
      renderLanguagesTable(tracks, opts.ascii)
      return
    }

    const fmt = (opts.format ?? config.subtitles.defaultFormat) as SubtitleFormat
    if (!SUBTITLE_FORMATS.includes(fmt)) {
      throw new Error(`Invalid format "${fmt}". Allowed: ${SUBTITLE_FORMATS.join(', ')}`)
    }

    const cfg: SubtitlesCfg = {
      videoId,
      lang: opts.lang ?? config.subtitles.defaultLanguage,
      format: fmt,
      autoGenerated: opts.auto || config.subtitles.preferAutoGenerated,
      outputDir: opts.output ?? config.subtitles.outputDir,
      stdout: opts.stdout,
      list: false,
      search: opts.search ?? null,
    }

    const content = await fetchSubtitles(cfg)

    // --search mode
    if (cfg.search) {
      const entries = parseSrt(content)
      const matches = searchInSubtitles(entries, cfg.search)
      renderSearchResults(matches, opts.ascii)
      return
    }

    // --stdout mode
    if (cfg.stdout) {
      // eslint-disable-next-line no-console
      console.log(content)
      return
    }

    const outPath = `${resolveHome(cfg.outputDir)}/${cfg.videoId}.${cfg.lang}.${cfg.format}`
    // eslint-disable-next-line no-console
    console.log(`Subtitles saved to: ${outPath}`)
  })
