import fs from 'fs'
import path from 'path'

import { resolveHome } from '../../config'
import {
  checkYtdlp,
  listSubs,
  downloadSubs,
  getVideoInfo,
  SubtitleTrack,
} from '../../lib/ytdlp'
import { SubtitlesCfg, SearchMatch } from './types'

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface TimestampedEntry {
  timestamp: string
  text: string
}

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

/**
 * Parses SRT-formatted subtitle content into an array of timestamped entries.
 *
 * Each SRT block looks like:
 *   1
 *   00:00:01,000 --> 00:00:04,000
 *   Hello world, this is a test.
 *
 * Blocks with fewer than 3 lines or without a valid timestamp line are skipped.
 */
export function parseSrt(content: string): TimestampedEntry[] {
  if (!content.trim()) {
    return []
  }

  const blocks = content.trim().split(/\n\n+/)
  const entries: TimestampedEntry[] = []

  for (const block of blocks) {
    const lines = block.split('\n')

    if (lines.length < 3) {
      continue
    }

    // line 1 should be a timestamp like "00:00:01,000 --> 00:00:04,000"
    const tsMatch = lines[1].match(/^(\d{2}:\d{2}:\d{2}),\d{3}\s+-->/)
    if (!tsMatch) {
      continue
    }

    const timestamp = tsMatch[1]
    const text = lines.slice(2).join(' ')

    entries.push({ timestamp, text })
  }

  return entries
}

/**
 * Searches subtitle entries for a query string (case-insensitive).
 * Returns all entries whose text contains the query.
 */
export function searchInSubtitles(
  entries: TimestampedEntry[],
  query: string,
): SearchMatch[] {
  const lowerQuery = query.toLowerCase()

  return entries
    .filter((entry) => entry.text.toLowerCase().includes(lowerQuery))
    .map((entry) => ({ timestamp: entry.timestamp, text: entry.text }))
}

// ---------------------------------------------------------------------------
// Async functions (I/O)
// ---------------------------------------------------------------------------

/**
 * Lists all available subtitle tracks for a video.
 */
export async function listLanguages(
  videoId: string,
): Promise<SubtitleTrack[]> {
  await checkYtdlp()
  return listSubs(videoId)
}

/**
 * Fetches subtitle content for a video, using disk cache when available.
 *
 * 1. Resolves the output directory (expanding ~).
 * 2. Checks for an existing cached file at `<outputDir>/<videoId>.<lang>.<format>`.
 * 3. If not cached, downloads via yt-dlp and reads the resulting file.
 * 4. Throws if the file is still not found after download.
 */
export async function fetchSubtitles(cfg: SubtitlesCfg): Promise<string> {
  await checkYtdlp()

  const outputDir = resolveHome(cfg.outputDir)
  const fileName = `${cfg.videoId}.${cfg.lang}.${cfg.format}`
  const filePath = path.join(outputDir, fileName)

  // Check disk cache
  if (fs.existsSync(filePath)) {
    return fs.readFileSync(filePath, 'utf-8')
  }

  // Create output directory if needed
  fs.mkdirSync(outputDir, { recursive: true, mode: 0o755 })

  // Download subtitles
  await downloadSubs(cfg.videoId, {
    lang: cfg.lang,
    format: cfg.format,
    autoGenerated: cfg.autoGenerated,
    outputDir,
  })

  // Read the downloaded file
  if (!fs.existsSync(filePath)) {
    throw new Error(
      `Subtitle file not found at ${filePath}. ` +
        'The requested language or format may not be available. ' +
        'Use --list to see available subtitle tracks.',
    )
  }

  return fs.readFileSync(filePath, 'utf-8')
}

/**
 * Fetches video metadata and returns a clean subset of fields.
 */
export async function fetchVideoInfo(
  videoId: string,
): Promise<{
  title: string
  channel: string
  duration: number
  description: string
  uploadDate: string
  viewCount: number
}> {
  await checkYtdlp()

  const info = await getVideoInfo(videoId)

  return {
    title: (info.title as string) ?? '',
    channel: (info.channel as string) ?? (info.uploader as string) ?? '',
    duration: (info.duration as number) ?? 0,
    description: (info.description as string) ?? '',
    uploadDate: (info.upload_date as string) ?? '',
    viewCount: (info.view_count as number) ?? 0,
  }
}
