export type SubtitleFormat = 'srt' | 'vtt' | 'json3' | 'srv1' | 'srv2' | 'srv3' | 'lrc' | 'txt'

export const SUBTITLE_FORMATS: SubtitleFormat[] = ['srt', 'vtt', 'json3', 'srv1', 'srv2', 'srv3', 'lrc', 'txt']

export interface SubtitlesCfg {
  videoId: string
  lang: string
  format: SubtitleFormat
  autoGenerated: boolean
  outputDir: string
  stdout: boolean
  list: boolean
  search: string | null
}

export interface SearchMatch {
  timestamp: string
  text: string
}
