import Table from 'cli-table3'
import type { SubtitleTrack } from '../../lib/ytdlp'
import type { SearchMatch } from './types'

const ASCII_CHARS = {
  top: '-', 'top-mid': '+', 'top-left': '+', 'top-right': '+',
  bottom: '-', 'bottom-mid': '+', 'bottom-left': '+', 'bottom-right': '+',
  left: '|', 'left-mid': '+', mid: '-', 'mid-mid': '+',
  right: '|', 'right-mid': '+', middle: '|',
}

export function renderLanguagesTable(tracks: SubtitleTrack[], ascii: boolean): void {
  if (tracks.length === 0) {
    // eslint-disable-next-line no-console
    console.log('No subtitles available for this video.')
    return
  }

  const table = new Table({
    head: ['Language', 'Name', 'Auto-generated'],
    style: { border: [], head: [] },
    chars: ascii ? ASCII_CHARS : undefined,
  })

  for (const t of tracks) {
    table.push([t.lang, t.name, t.isAutoGenerated ? 'yes' : 'no'])
  }

  // eslint-disable-next-line no-console
  console.log(table.toString())
}

export function renderSearchResults(matches: SearchMatch[], ascii: boolean): void {
  if (matches.length === 0) {
    // eslint-disable-next-line no-console
    console.log('No matches found.')
    return
  }

  const table = new Table({
    head: ['Timestamp', 'Text'],
    colWidths: [14, Math.max(60, (process.stdout.columns || 120) - 18)],
    wordWrap: true,
    style: { border: [], head: [] },
    chars: ascii ? ASCII_CHARS : undefined,
  })

  for (const m of matches) {
    table.push([m.timestamp, m.text])
  }

  // eslint-disable-next-line no-console
  console.log(table.toString())
}
