import os from 'os'
import fs from 'fs'
import path from 'path'

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface SubtitlesConfig {
  outputDir: string
  defaultFormat: string
  defaultLanguage: string
  preferAutoGenerated: boolean
  poToken: string
}

export interface CacheConfig {
  ttl: number
  dir: string
}

export interface AppConfig {
  subtitles: SubtitlesConfig
  cache: CacheConfig
  authorBonus: number
}

// ---------------------------------------------------------------------------
// Defaults
// ---------------------------------------------------------------------------

export const DEFAULTS: AppConfig = {
  subtitles: {
    outputDir: '~/youtools/subtitles',
    defaultFormat: 'srt',
    defaultLanguage: 'en',
    preferAutoGenerated: false,
    poToken: '',
  },
  cache: {
    ttl: 3600,
    dir: '~/.cache/youtools',
  },
  authorBonus: 1000,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Expands a leading `~/` to the current user's home directory.
 * All other paths are returned unchanged.
 */
export function resolveHome(p: string): string {
  if (p.startsWith('~/')) {
    return path.join(os.homedir(), p.slice(2))
  }
  return p
}

/**
 * Recursively deep-merges `override` into a *copy* of `base`.
 * - Nested plain objects are merged recursively.
 * - Scalar values in `override` replace those in `base`.
 * - The original `base` object is never mutated.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function deepMerge<T extends Record<string, any>>(
  base: T,
  override: Record<string, unknown>,
): T {
  const result: Record<string, unknown> = {}

  for (const key of Object.keys(base)) {
    const baseVal = (base as Record<string, unknown>)[key]
    const overVal = override[key]

    if (
      overVal !== undefined &&
      isPlainObject(baseVal) &&
      isPlainObject(overVal)
    ) {
      result[key] = deepMerge(
        baseVal as Record<string, unknown>,
        overVal as Record<string, unknown>,
      )
    } else if (overVal !== undefined) {
      result[key] = overVal
    } else {
      result[key] = isPlainObject(baseVal)
        ? deepMerge(baseVal as Record<string, unknown>, {})
        : baseVal
    }
  }

  return result as T
}

function isPlainObject(val: unknown): val is Record<string, unknown> {
  return typeof val === 'object' && val !== null && !Array.isArray(val)
}

// ---------------------------------------------------------------------------
// Config loading
// ---------------------------------------------------------------------------

const CONFIG_PATH = path.join(
  os.homedir(),
  '.config',
  'youtools',
  'youtools.json',
)

let cachedConfig: AppConfig | null = null

/**
 * Loads the user config from `~/.config/youtools/youtools.json`, deep-merges
 * it with DEFAULTS, and caches the result. If the file is missing or contains
 * invalid JSON the defaults are returned as-is.
 */
export function loadConfig(): AppConfig {
  if (cachedConfig) {
    return cachedConfig
  }

  let userConfig: Record<string, unknown> = {}

  try {
    const raw = fs.readFileSync(CONFIG_PATH, 'utf-8')
    userConfig = JSON.parse(raw) as Record<string, unknown>
  } catch {
    // File missing or invalid JSON — use defaults
  }

  const merged = deepMerge(DEFAULTS, userConfig)
  cachedConfig = merged
  return merged
}

/**
 * Clears the cached config so the next `loadConfig()` call re-reads from disk.
 * Intended for use in tests only.
 */
export function _resetConfig(): void {
  cachedConfig = null
}
