import os from 'os'
import fs from 'fs'
import path from 'path'
import {
  resolveHome,
  deepMerge,
  DEFAULTS,
  loadConfig,
  _resetConfig,
} from './config'

describe('resolveHome', () => {
  it('expands ~/ to os.homedir()', () => {
    const result = resolveHome('~/foo/bar')
    expect(result).toBe(path.join(os.homedir(), 'foo/bar'))
  })

  it('leaves absolute paths unchanged', () => {
    expect(resolveHome('/usr/local/bin')).toBe('/usr/local/bin')
  })

  it('leaves paths without ~/ prefix unchanged', () => {
    expect(resolveHome('relative/path')).toBe('relative/path')
  })
})

describe('deepMerge', () => {
  it('merges nested objects recursively', () => {
    const base = { a: { b: 1, c: 2 }, d: 3 }
    const override = { a: { b: 10 } }
    const result = deepMerge(base, override)
    expect(result).toEqual({ a: { b: 10, c: 2 }, d: 3 })
  })

  it('overrides scalar values', () => {
    const base = { x: 'hello', y: 42 }
    const override = { x: 'world' }
    expect(deepMerge(base, override)).toEqual({ x: 'world', y: 42 })
  })

  it('handles empty override', () => {
    const base = { a: 1, b: { c: 2 } }
    const result = deepMerge(base, {})
    expect(result).toEqual({ a: 1, b: { c: 2 } })
  })

  it('does not mutate the base object', () => {
    const base = { a: { b: 1 } }
    const override = { a: { b: 2 } }
    deepMerge(base, override)
    expect(base.a.b).toBe(1)
  })
})

describe('DEFAULTS', () => {
  it('has correct subtitles config', () => {
    expect(DEFAULTS.subtitles).toEqual({
      outputDir: '~/youtools/subtitles',
      defaultFormat: 'srt',
      defaultLanguage: 'en',
      preferAutoGenerated: false,
    })
  })

  it('has correct cache config', () => {
    expect(DEFAULTS.cache).toEqual({
      ttl: 3600,
      dir: '~/.cache/youtools',
    })
  })

  it('has correct authorBonus', () => {
    expect(DEFAULTS.authorBonus).toBe(1000)
  })
})

describe('loadConfig', () => {
  const configDir = path.join(os.homedir(), '.config', 'youtools')
  const configFile = path.join(configDir, 'youtools.json')

  beforeEach(() => {
    _resetConfig()
  })

  afterEach(() => {
    // Clean up any config file we created
    try {
      fs.unlinkSync(configFile)
    } catch {
      // file may not exist, that's fine
    }
  })

  it('returns defaults when no config file exists', () => {
    // Make sure the config file does not exist
    try {
      fs.unlinkSync(configFile)
    } catch {
      // ignore
    }
    const config = loadConfig()
    expect(config).toEqual(DEFAULTS)
  })

  it('merges user config with defaults', () => {
    fs.mkdirSync(configDir, { recursive: true })
    fs.writeFileSync(configFile, JSON.stringify({ authorBonus: 500 }))
    const config = loadConfig()
    expect(config.authorBonus).toBe(500)
    expect(config.subtitles).toEqual(DEFAULTS.subtitles)
    expect(config.cache).toEqual(DEFAULTS.cache)
  })

  it('deep-merges nested user config', () => {
    fs.mkdirSync(configDir, { recursive: true })
    fs.writeFileSync(
      configFile,
      JSON.stringify({ subtitles: { defaultLanguage: 'es' } }),
    )
    const config = loadConfig()
    expect(config.subtitles.defaultLanguage).toBe('es')
    expect(config.subtitles.defaultFormat).toBe('srt')
  })

  it('returns defaults when config file has invalid JSON', () => {
    fs.mkdirSync(configDir, { recursive: true })
    fs.writeFileSync(configFile, 'not valid json {{{')
    const config = loadConfig()
    expect(config).toEqual(DEFAULTS)
  })

  it('caches the result across calls', () => {
    const config1 = loadConfig()
    const config2 = loadConfig()
    expect(config1).toBe(config2) // same reference
  })

  it('returns fresh result after _resetConfig', () => {
    const config1 = loadConfig()
    _resetConfig()
    const config2 = loadConfig()
    expect(config1).toEqual(config2)
    expect(config1).not.toBe(config2) // different references
  })
})
