#!/usr/bin/env node
import 'dotenv/config'

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'

import {
  listLanguages,
  fetchSubtitles,
  searchInSubtitles,
  parseSrt,
  fetchVideoInfo,
} from './modules/subtitles/service'
import { loadConfig } from './config'
import { SubtitlesCfg, SubtitleFormat } from './modules/subtitles/types'

// ---------------------------------------------------------------------------
// Summary prompt templates
// ---------------------------------------------------------------------------

const SUMMARY_PROMPTS: Record<string, string> = {
  brief:
    'Based on the video subtitles below, provide:\n' +
    '1. A brief summary (3-5 sentences)\n' +
    '2. 2-3 main ideas or key takeaways\n' +
    '3. A checklist of 5-10 actionable items or key points\n\n' +
    'Format the response in markdown.',
  detailed:
    'Based on the video subtitles below, provide a comprehensive summary:\n' +
    '1. Detailed overview (1-2 paragraphs)\n' +
    '2. All major topics covered with key details\n' +
    '3. Notable quotes or statements\n' +
    '4. A structured outline of the content\n\n' +
    'Format the response in markdown.',
  checklist:
    'Based on the video subtitles below, extract:\n' +
    '1. Every actionable item, tip, or recommendation mentioned\n' +
    '2. Format as a markdown checklist (- [ ] item)\n' +
    '3. Group by topic if applicable\n' +
    '4. Include timestamps where possible',
}

// ---------------------------------------------------------------------------
// MCP Server
// ---------------------------------------------------------------------------

const server = new McpServer({
  name: 'youtools',
  version: '0.1.0',
})

// Tool 1: list_subtitle_languages
server.registerTool(
  'list_subtitle_languages',
  {
    description: 'List available subtitle languages for a YouTube video',
    inputSchema: {
      videoId: z.string(),
    },
  },
  async ({ videoId }) => {
    const config = loadConfig()
    const tracks = await listLanguages(videoId, config.subtitles.poToken || undefined)
    return {
      content: [{ type: 'text' as const, text: JSON.stringify(tracks, null, 2) }],
    }
  },
)

// Tool 2: get_subtitles
server.registerTool(
  'get_subtitles',
  {
    description:
      'Download and return subtitles for a YouTube video. Caches to disk.',
    inputSchema: {
      videoId: z.string(),
      lang: z.string().optional(),
      format: z.string().optional(),
    },
  },
  async ({ videoId, lang, format }) => {
    const config = loadConfig()
    const cfg: SubtitlesCfg = {
      videoId,
      lang: lang ?? config.subtitles.defaultLanguage,
      format: (format ?? config.subtitles.defaultFormat) as SubtitleFormat,
      autoGenerated: config.subtitles.preferAutoGenerated,
      outputDir: config.subtitles.outputDir,
      stdout: false,
      list: false,
      search: null,
      poToken: config.subtitles.poToken,
    }
    const text = await fetchSubtitles(cfg)
    return {
      content: [{ type: 'text' as const, text }],
    }
  },
)

// Tool 3: search_in_subtitles
server.registerTool(
  'search_in_subtitles',
  {
    description:
      'Search for text in video subtitles, returns matching lines with timestamps',
    inputSchema: {
      videoId: z.string(),
      query: z.string(),
      lang: z.string().optional(),
    },
  },
  async ({ videoId, query, lang }) => {
    const config = loadConfig()
    const cfg: SubtitlesCfg = {
      videoId,
      lang: lang ?? config.subtitles.defaultLanguage,
      format: 'srt',
      autoGenerated: config.subtitles.preferAutoGenerated,
      outputDir: config.subtitles.outputDir,
      stdout: false,
      list: false,
      search: null,
      poToken: config.subtitles.poToken,
    }
    const srtContent = await fetchSubtitles(cfg)
    const entries = parseSrt(srtContent)
    const matches = searchInSubtitles(entries, query)
    return {
      content: [
        { type: 'text' as const, text: JSON.stringify(matches, null, 2) },
      ],
    }
  },
)

// Tool 4: get_video_info
server.registerTool(
  'get_video_info',
  {
    description:
      'Get metadata for a YouTube video (title, channel, duration, description, views)',
    inputSchema: {
      videoId: z.string(),
    },
  },
  async ({ videoId }) => {
    const config = loadConfig()
    const info = await fetchVideoInfo(videoId, config.subtitles.poToken || undefined)
    return {
      content: [
        { type: 'text' as const, text: JSON.stringify(info, null, 2) },
      ],
    }
  },
)

// Tool 5: summarize_video
server.registerTool(
  'summarize_video',
  {
    description:
      'Get video subtitles with a summarization prompt. The LLM agent uses the returned prompt to generate the summary.',
    inputSchema: {
      videoId: z.string(),
      lang: z.string().optional(),
      format: z.string().optional(),
    },
  },
  async ({ videoId, lang, format }) => {
    const config = loadConfig()
    const cfg: SubtitlesCfg = {
      videoId,
      lang: lang ?? config.subtitles.defaultLanguage,
      format: 'srt',
      autoGenerated: config.subtitles.preferAutoGenerated,
      outputDir: config.subtitles.outputDir,
      stdout: false,
      list: false,
      search: null,
      poToken: config.subtitles.poToken,
    }
    const content = await fetchSubtitles(cfg)

    // Determine prompt based on format
    const style = format ?? 'brief'
    let prompt: string
    if (style.startsWith('custom:')) {
      prompt = style.slice('custom:'.length)
    } else {
      prompt = SUMMARY_PROMPTS[style] ?? SUMMARY_PROMPTS.brief
    }

    return {
      content: [
        {
          type: 'text' as const,
          text: `${prompt}\n\n---\n\n## Video Subtitles\n\n${content}`,
        },
      ],
    }
  },
)

// ---------------------------------------------------------------------------
// Connect to stdio transport
// ---------------------------------------------------------------------------

async function main() {
  const transport = new StdioServerTransport()
  await server.connect(transport)
}

main().catch((err) => {
  console.error('MCP server fatal error:', err)
  process.exit(1)
})
